# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
DATABASE:
  URL: ${DATABASE_URL}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    WEB: '9879dbb7cfe39e4d-01'
    KJV: 'de4e12af7f28f599-02'
CLOUDINARY:
  URL: ${CLOUDINARY_URL}

CONTENT:
  SERMON_CHANNEL_ID: cbc0994a-97f1-471a-a7d5-4eff59d8a389
  TYPES:
    - ContentSeriesContentItem
    - DevotionalContentItem
    - MediaContentItem
    - UniversalContentItem
    - WeekendContentItem
    - ContentItem

SUGGESTED_FOLLOWS:
  - email: vincent@differential.com
  - email: conrad@differential.com

TABS:
  HOME:
    - type: ActionBar
      title: Welcome to Apollos
      actions:
        [
          {
            title: Check In,
            icon: check,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
        ]
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - c7f43eb9-2200-4267-ab28-871e0d5e785f
            - 3dfe7149-136b-4134-bd91-fdd935ef2221
      type: HeroList
      primaryAction:
        # Right now, you hardcode exactly what GraphQL should return.
        # Long term, we hope to have a more sophisticated mechanism for driving this field
        action: OPEN_NODE
        title: 'Read More'
        relatedNode:
          __typename: UniversalContentItem
          id: a2c42d1d-98c8-46fb-aeea-603bc569cf7d
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - algorithms:
        - type: CAMPAIGN_ITEMS
          channelIds:
            - 4b23ebc9-248e-4092-99f9-8829e1b6f1cc
      type: HeroList
      isFeatured: true
      subtitle: Featured
    - title: FOR YOU
      algorithms: [SERMON_CHILDREN, PERSONA_FEED]
      subtitle: Explore what God calls you to today
      type: ActionList
    - algorithms: [SERIES_IN_PROGRESS]
      subtitle: Continue
      type: HorizontalCardList
    - title: RECOMMENDED
      algorithms: [SERMON_CHILDREN]
      subtitle: For Him
      type: VerticalCardList
    - title: BULLETIN
      subtitle: What's happening at apollos?
      type: ActionList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 13
        - type: UPCOMING_EVENTS

  READ:
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - c7f43eb9-2200-4267-ab28-871e0d5e785f
            limit: 3
      type: HorizontalCardList
      subtitle: Podcast Messages
      primaryAction:
        action: OPEN_CHANNEL
        title: 'Read More'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
          title: Podcast Messages
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - d9da719f-84ef-4cf0-9875-22fea4bf09eb
            limit: 3
      type: HorizontalCardList
      subtitle: Devotionals
      primaryAction:
        action: OPEN_CHANNEL
        title: 'Read More'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:d9da719f-84ef-4cf0-9875-22fea4bf09eb
          title: Devotionals

  WATCH:
    - algorithms:
        - type: LATEST_SERIES_CHILDREN
          arguments:
            channelId: 8f0a93f5-ccec-4cc1-8fd8-06afe5982f7b
      type: HeroList
      title: Catch up
      subtitle: Latest Series
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
      type: VerticalCardList
      subtitle: All series
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 8f0a93f5-ccec-4cc1-8fd8-06afe5982f7b
            limit: 3
      type: HorizontalCardList
      subtitle: Sermons
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
            limit: 3
      type: HorizontalCardList
      subtitle: Podcasts
      primaryAction:
        action: OPEN_CHANNEL
        title: 'Read More'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
          title: Podcasts
    - algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
            limit: 3
      type: HorizontalCardList
      title: Videos
      primaryAction:
        action: OPEN_CHANNEL
        title: 'Read More'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:f4a5890c-4af5-4d9f-afe3-5d1c6aa85419
          title: Videos

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
  CONNECT:
    - type: FollowPeople
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]
