# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

def bump_version_code()
    s = File.read("../android/app/build.gradle")
    versionCode = number_of_commits
    s[/versionCode\s+(\d+)/, 1] = (versionCode).to_s
    f = File.new('../android/app/build.gradle', 'w')
    f.write(s)
    f.close
end

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end


platform :ios do

  desc "Generate new provisioning profiles and certificates for app and push notifications"
  lane :certs do
    app_store_connect_api_key(key_filepath: "ios/apollos.p8")
    match(type: 'development', app_identifier: [ENV["DELIVER_APP_IDENTIFIER"], "#{ENV["DELIVER_APP_IDENTIFIER"]}.OneSignalNotificationServiceExtension"],)
    match(type: 'appstore', app_identifier: [ENV["DELIVER_APP_IDENTIFIER"], "#{ENV["DELIVER_APP_IDENTIFIER"]}.OneSignalNotificationServiceExtension"],)
    get_push_certificate
  end

  desc "Push a new internal build to TestFlight"
  lane :deploy do

    # get project name
    proj = Dir.glob("../ios/*.xcworkspace")[0][7..-13]

    app_store_connect_api_key(key_filepath: "ios/apollos.p8", in_house: false)
    setup_ci
    match(
      type: 'appstore',
      app_identifier: [ENV["DELIVER_APP_IDENTIFIER"], "#{ENV["DELIVER_APP_IDENTIFIER"]}.OneSignalNotificationServiceExtension"],
      readonly: true
    )
    increment_build_number(build_number: number_of_commits, xcodeproj: "ios/" << proj << ".xcodeproj")
    build_app(workspace: "ios/" << proj << ".xcworkspace", scheme: proj)
    changelog_from_git_commits
    testflight
  end

  desc "Promote the most recent Testflight version to production"
  lane :production do
    app_store_connect_api_key(key_filepath: "ios/apollos.p8", in_house: false)
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: false,
      submit_for_review: true,
      automatic_release: false,
      submission_information: {
        add_id_info_uses_idfa: false
      },
      reject_if_possible: true,
      run_precheck_before_submit: false
    )
  end
end

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    bump_version_code
    gradle(task: 'clean', project_dir: 'android')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android')
    changelog_from_git_commits

    s = File.read("../android/app/build.gradle")
    package_name = s[/applicationId\s+"([\w+\.]*)"/, 1]

    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
      json_key: "android/key.json",
      package_name: package_name
    )
  end
end

error do |lane, exception|
  s = File.read("../app.json")
  app_name = s[/"name": "(.*)",/, 1]
  slack(message: app_name << " - " << exception.to_s, success: false)
end
