# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.differential.apollos', type: 'development', readonly: true)
    match(app_identifier: 'com.differential.apollos', type: 'appstore', readonly: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :deploy do
    setup_ci
    certificates
    increment_build_number(build_number: number_of_commits, xcodeproj: "ios/apolloschurchapp.xcodeproj")
    build_app(workspace: "ios/apolloschurchapp.xcworkspace", scheme: "apolloschurchappprod")
    upload_to_testflight
  end
end

platform :android do

  # necessary because setting gradle properties doesn't seem to be working
  desc "Bumps Android versionCode"
  lane :bump_version_code do
    path = '../android/app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = number_of_commits
    s[re, 1] = (versionCode).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    bump_version_code
    gradle(task: 'clean', project_dir: 'android')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android')
    upload_to_play_store(track: "internal")
  end
end
