require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
target 'apolloschurchapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  target 'apolloschurchappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  post_install do |installer|
    flipper_post_install(installer)
      installer.pods_project.targets.each do |target|
       if target.name == 'react-native-config'
         phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
         phase.shell_script = "cd ../../"\
         " && RNC_ROOT=./node_modules/react-native-config/"\
         " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
         " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

         target.build_phases << phase
         target.build_phases.move(phase,0)
       end
      end
  end
end

target 'apolloschurchapp-tvOS' do
  # Pods for apolloschurchapp-tvOS

  target 'apolloschurchapp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end