name: Deploy iOS

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.x

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: |
        cd apolloschurchapp
        yarn

    - name: Create Keychain
      run: bundle exec fastlane run create_keychain name:"github.keychain" default_keychain:"true" unlock:"true"


    - name: Fastlane Deploy
      run: bundle exec fastlane ios deploy
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
