name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # heroku only uses yarn if there's a yarn.lock file
      - name: Use Yarn
        run: touch yarn.lock
        working-directory: apollos-church-api

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "apollos-church-api"
          heroku_email: "apps@apollos.app"
          appdir: apollos-church-api
          healthcheck: ${{ secrets.APP_DATA_URL }}/health
          rollbackonhealthcheckfailed: true
          checkstring: "ok"
          delay: 300

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Publish Schema
        run: npx apollo schema:publish --endpoint=${{ secrets.APP_DATA_URL }}
        env:
          ENGINE_API_KEY: ${{ secrets.ENGINE_API_KEY }}
