name: Deploy Android

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.x

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: |
        cd apolloschurchapp
        yarn

    # required to build
    - name: Generate Stores
      run: yarn generate-stories

    - name: Get Introspection Data
      run: node ./scripts/get-introspection-data.js
      env:
        APP_DATA_URL: grep APP_DATA_URL .env.production | sed "s/APP_DATA_URL=//"

    - name: Fastlane Deploy
      run: bundle exec fastlane android deploy
