name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
    - run: yarn --ignore-scripts

  eslint:
    needs: setup
    steps:

    - name: Lint
      run: yarn lint

  jest:
    needs: setup
    steps:

    - name: Test
      run: yarn test --forceExit

  codecov:
    needs: setup
    steps:

    - name: Generate Codecov
      run: yarn lerna run codecov

    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
