name: Tests CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: |
        npm install -g yarn
        yarn --ignore-scripts

    # - name: Install client dependencies
    #   run: yarn --ignore-scripts
    #   working-directory: ./apolloschurchapp

    # - name: Install api dependencies
    #   run: yarn --ignore-scripts
    #   working-directory: ./apollos-church-api

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test --forceExit
      working-directory: ./apolloschurchapp

    - name: Generate Codecov
      run: yarn lerna run codecov

    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
