name: Tests CI

on:
  pull_request:
    branches: [master, develop]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn --ignore-scripts

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: yarn lint

    - name: Test
      run: yarn test --forceExit
      working-directory: ./apolloschurchapp

    - name: Generate Codecov
      run: yarn lerna run codecov

    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
